name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Lint affected projects
        run: npx nx affected:lint --base=HEAD~1 --head=HEAD
      - name: Run unit tests for affected projects
        run: npx nx affected:test --base=HEAD~1 --head=HEAD --testPathIgnorePatterns=providerVerification.test.ts
